#!/bin/bash
set -euo pipefail

# Check for branch parameters
branch=${BUILDKITE_PLUGIN_GIT_CLONE_BRANCH-""}
BRANCH_PARAM=
if [ ! -z ${branch} ]; then
    BRANCH_PARAM="--branch ${branch}"
fi

echo "cloning repository ${BUILDKITE_PLUGIN_GIT_CLONE_REPOSITORY} ${BRANCH_PARAM}"

git clone ${BUILDKITE_PLUGIN_GIT_CLONE_REPOSITORY} ${BRANCH_PARAM}
